server:
  port: 9090
logging:
  level:
    org:
      atmosphere: warn
spring:
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${BCUK_BOT_DISCORD_CLIENT_ID}
            client-secret: ${BCUK_BOT_DISCORD_CLIENT_SECRET}
            clientAuthenticationMethod: none
            authorizationGrantType: authorization_code
            scope:
              - identify
              - guilds
            redirect-uri: "{baseUrl}/login/oauth2/code/discord"
            clientName: BCUK BOT
        provider:
          discord:
            authorizationUri: https://discord.com/api/oauth2/authorize
            tokenUri: https://discord.com/api/oauth2/token
            userInfoUri: https://discord.com/api/users/@me
            userNameAttribute: username
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bcukbot?serverTimezone=UTC
    username: ${BCUK_BOT_SQL_USER}
    password: ${BCUK_BOT_SQL_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      enabled: false
